default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: railsuser
  password: railspass
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: hello_rails_development

test:
  <<: *default
  database: hello_rails_test

production:
  <<: *default
  database: hello_rails_production
  username: hello_rails
  password: <%= ENV['HELLO_RAILS_DATABASE_PASSWORD'] %>